version: 0.0
os: linux
files:
  - source: docs
    destination:  /var/www/html
permissions:
  permissions-specifications
hooks:
  BeforeInstall:
    - location: pre-deploy.sh
      timeout: 30
  AfterInstall:
    - location: post-deploy.sh
      timeout: 30